# Generated by Django 6.0.2 on 2026-02-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('MEDICO', 'Médico'), ('PACIENTE', 'Paciente'), ('SECRETARIA', 'Secretaria')], default='PACIENTE', max_length=50),
        ),
    ]
