# Generated by Django 6.0.2 on 2026-04-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_transaction_id', models.CharField(max_length=100, unique=True)),
                ('datos_json', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
