# Generated by Django 6.0.2 on 2026-05-05 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_paciente_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('especie', models.CharField(choices=[('PERRO', 'Perro'), ('GATO', 'Gato'), ('AVE', 'Ave'), ('CONEJO', 'Conejo'), ('ROEDOR', 'Roedor (cuy, hámster, etc.)'), ('REPTIL', 'Reptil'), ('PEZ', 'Pez'), ('OTRO', 'Otro')], max_length=10)),
                ('raza', models.CharField(blank=True, max_length=80)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, help_text='Kg', max_digits=6, null=True)),
                ('esterilizado', models.BooleanField(default=False)),
                ('chip_id', models.CharField(blank=True, help_text='Microchip / ID de identificación', max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='mascotas/')),
                ('alergias', models.TextField(blank=True)),
                ('enfermedades_cronicas', models.TextField(blank=True)),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='paciente.paciente')),
            ],
        ),
    ]
