# Generated by Django 6.0.2 on 2026-04-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0003_corregir_especialidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='intervalo_minutos',
            field=models.PositiveIntegerField(default=30, help_text='Duración de cada cita en minutos'),
        ),
    ]
