# Generated by Django 6.0.2 on 2026-04-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0004_add_intervalo_minutos'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medico',
            name='pais',
            field=models.CharField(blank=True, default='Ecuador', max_length=100),
        ),
        migrations.AddField(
            model_name='medico',
            name='sector',
            field=models.CharField(blank=True, choices=[('', '-- Seleccionar --'), ('NORTE', 'Norte'), ('CENTRO', 'Centro'), ('SUR', 'Sur'), ('VALLES', 'Valles'), ('OTRO', 'Otro')], max_length=10),
        ),
    ]
