# Generated by Django 6.0.2 on 2026-05-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0008_agregar_veterinaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='en_periodo_prueba',
            field=models.BooleanField(default=True, help_text='True = trial gratis; False = suscripción pagada'),
        ),
        migrations.AddField(
            model_name='medico',
            name='fecha_fin_suscripcion',
            field=models.DateField(blank=True, help_text='Fecha en la que vence la suscripción (prueba o pagada)', null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='fecha_inicio_suscripcion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
