# Generated by Django 6.0.2 on 2026-05-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0010_inicializar_suscripciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='registro_msp',
            field=models.CharField(blank=True, help_text='Número de Registro Profesional emitido por el MSP', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='registro_senescyt',
            field=models.CharField(blank=True, help_text='Número de registro SENESCYT (legacy)', max_length=50),
        ),
    ]
