# Generated by Django 6.0.2 on 2026-06-19 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0011_medico_registro_msp_alter_medico_registro_senescyt'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='plan_suscripcion',
            field=models.CharField(choices=[('ANUAL', 'Anual ($100/año)'), ('MENSUAL', 'Mensual ($10/mes)')], default='ANUAL', help_text='Plan elegido: ANUAL extiende 365 días; MENSUAL extiende 30 días', max_length=10),
        ),
    ]
