# Generated by Django 6.0.2 on 2026-06-22 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0012_medico_plan_suscripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='plan_suscripcion',
        ),
    ]
