# Generated by Django 6.0.2 on 2026-08-05 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0013_remove_medico_plan_suscripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaPublica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('publicada', models.BooleanField(default=False, help_text='Si está marcada, la ficha es visible en /p/<slug>/')),
                ('titulo_profesional', models.CharField(blank=True, max_length=120, verbose_name='título o especialidad')),
                ('descripcion', models.TextField(blank=True)),
                ('servicios', models.TextField(blank=True, help_text='Uno por línea')),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('mapa_url', models.URLField(blank=True, help_text='Se arma automáticamente al marcar tu ubicación en el mapa.', verbose_name='enlace de Google Maps')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('horarios', models.TextField(blank=True, help_text='Uno por línea')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('medico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha', to='medico.medico')),
            ],
            options={
                'verbose_name': 'Ficha pública',
                'verbose_name_plural': 'Fichas públicas',
            },
        ),
    ]
