# Generated by Django 6.0.2 on 2026-08-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0014_fichapublica'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichapublica',
            name='precio_consulta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Opcional. Si lo dejas vacío, no se muestra el precio en tu página.', max_digits=10, null=True, verbose_name='valor de la consulta'),
        ),
    ]
