# Generated by Django 6.0.2 on 2026-04-18 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medico', '0002_secretaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaElectronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_acceso', models.CharField(max_length=49, unique=True)),
                ('numero_secuencial', models.CharField(max_length=20)),
                ('secuencial_numero', models.PositiveIntegerField()),
                ('receptor_tipo_id', models.CharField(choices=[('04', 'RUC'), ('05', 'Cédula'), ('06', 'Pasaporte'), ('07', 'Consumidor Final')], default='05', max_length=2)),
                ('receptor_identificacion', models.CharField(max_length=20)),
                ('receptor_nombre', models.CharField(max_length=300)),
                ('receptor_email', models.EmailField(blank=True, max_length=254)),
                ('receptor_direccion', models.CharField(blank=True, default='N/A', max_length=300)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('iva_valor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.CharField(default='Registro de suscripción - Sistema Salud', max_length=300)),
                ('xml_sin_firma', models.TextField(blank=True)),
                ('xml_firmado', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de envío'), ('ENVIADA', 'Enviada al SRI'), ('AUTORIZADA', 'Autorizada por SRI'), ('RECHAZADA', 'Rechazada por SRI'), ('ERROR', 'Error en el proceso')], default='PENDIENTE', max_length=20)),
                ('numero_autorizacion', models.CharField(blank=True, max_length=100)),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('respuesta_sri', models.JSONField(blank=True, null=True)),
                ('mensajes_sri', models.TextField(blank=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='medico.medico')),
            ],
            options={
                'verbose_name': 'Factura Electrónica',
                'verbose_name_plural': 'Facturas Electrónicas',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='SecuencialFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establecimiento', models.CharField(default='001', max_length=3)),
                ('punto_emision', models.CharField(default='001', max_length=3)),
                ('ultimo_secuencial', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Secuencial de Factura',
                'unique_together': {('establecimiento', 'punto_emision')},
            },
        ),
    ]
