# Generated by Django 6.0.2 on 2026-04-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaelectronica',
            name='descripcion',
            field=models.CharField(default='Registro de suscripción - VertexSalud', max_length=300),
        ),
    ]
