# Generated by Django 6.0.2 on 2026-05-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_alter_facturaelectronica_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaelectronica',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de envío'), ('ENVIADA', 'Enviada al SRI'), ('AUTORIZADA', 'Autorizada por SRI'), ('RECHAZADA', 'Rechazada por SRI'), ('ERROR', 'Error en el proceso'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=20),
        ),
    ]
