# Generated by Django 6.0.2 on 2026-06-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_alter_facturaelectronica_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaelectronica',
            name='payphone_client_transaction_id',
            field=models.CharField(blank=True, default='', help_text='clientTransactionId (UUID) que enviamos a PayPhone', max_length=100),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='payphone_transaction_id',
            field=models.CharField(blank=True, default='', help_text='ID retornado por PayPhone tras confirmación de pago', max_length=100),
        ),
    ]
