# Generated by Django 6.0.2 on 2026-07-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_facturaelectronica_payphone_client_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaelectronica',
            name='intentos_sri',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad de intentos de envío al SRI (se incrementa en cada retry).'),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='ultimo_intento_sri',
            field=models.DateTimeField(blank=True, help_text='Timestamp del último intento de envío al SRI.', null=True),
        ),
    ]
