# Generated by Django 6.0.2 on 2026-08-18 20:36

import django.db.models.deletion
import teleconsulta.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0007_cita_modalidad'),
        ('paciente', '0003_add_mascota'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeleconsultaSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala_id', models.CharField(default=teleconsulta.models._nuevo_sala_id, max_length=64, unique=True)),
                ('proveedor', models.CharField(default='jitsi', max_length=20)),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('CONSENTIMIENTO', 'Consentimiento pendiente'), ('PRECHECK', 'Verificación técnica'), ('SALA_ESPERA', 'En sala de espera'), ('EN_CURSO', 'En curso'), ('FINALIZADA', 'Finalizada'), ('FALLIDA', 'Falla técnica'), ('CANCELADA', 'Cancelada')], default='PROGRAMADA', max_length=20)),
                ('token', models.CharField(default=teleconsulta.models._nuevo_token, max_length=96, unique=True)),
                ('token_expira', models.DateTimeField(blank=True, null=True)),
                ('paciente_en_espera', models.BooleanField(default=False)),
                ('paciente_admitido', models.BooleanField(default=False)),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('ubicacion_declarada_paciente', models.CharField(blank=True, max_length=200)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teleconsulta', to='citas.cita')),
            ],
            options={
                'verbose_name': 'Sesión de teleconsulta',
                'verbose_name_plural': 'Sesiones de teleconsulta',
            },
        ),
        migrations.CreateModel(
            name='EventoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(help_text='usuario o paciente:token', max_length=150)),
                ('accion', models.CharField(max_length=80)),
                ('recurso', models.CharField(blank=True, max_length=160)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria', to='teleconsulta.teleconsultasesion')),
            ],
            options={
                'verbose_name': 'Evento de auditoría',
                'verbose_name_plural': 'Eventos de auditoría',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ConsentimientoTelesalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='TELESALUD', max_length=30)),
                ('version_documento', models.CharField(default='v1', max_length=10)),
                ('texto_documento', models.TextField(help_text='Texto exacto que el paciente aceptó')),
                ('aceptado', models.BooleanField(default=False)),
                ('aceptado_en', models.DateTimeField(blank=True, null=True)),
                ('aceptado_por', models.CharField(choices=[('PACIENTE', 'El propio paciente'), ('REPRESENTANTE', 'Representante legal / tutor')], default='PACIENTE', max_length=20)),
                ('representante_nombre', models.CharField(blank=True, max_length=150)),
                ('representante_cedula', models.CharField(blank=True, max_length=20)),
                ('representante_parentesco', models.CharField(blank=True, max_length=50)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('hash_documento', models.CharField(blank=True, max_length=64)),
                ('revocado', models.BooleanField(default=False)),
                ('revocado_en', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos_telesalud', to='paciente.paciente')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos', to='teleconsulta.teleconsultasesion')),
            ],
            options={
                'verbose_name': 'Consentimiento de telesalud',
                'verbose_name_plural': 'Consentimientos de telesalud',
                'ordering': ['-creado'],
            },
        ),
    ]
