# Generated by Django 6.0.2 on 2026-08-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsulta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teleconsultasesion',
            name='derivacion_motivo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teleconsultasesion',
            name='derivacion_tipo',
            field=models.CharField(blank=True, choices=[('PRESENCIAL', 'Atención presencial'), ('EMERGENCIA', 'Emergencia (ECU-911)')], max_length=20),
        ),
        migrations.AddField(
            model_name='teleconsultasesion',
            name='derivada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teleconsultasesion',
            name='estado',
            field=models.CharField(choices=[('PROGRAMADA', 'Programada'), ('CONSENTIMIENTO', 'Consentimiento pendiente'), ('PRECHECK', 'Verificación técnica'), ('SALA_ESPERA', 'En sala de espera'), ('EN_CURSO', 'En curso'), ('FINALIZADA', 'Finalizada'), ('DERIVADA', 'Derivada a presencial/emergencia'), ('FALLIDA', 'Falla técnica'), ('CANCELADA', 'Cancelada')], default='PROGRAMADA', max_length=20),
        ),
    ]
