# Generated by Django 6.0.2 on 2026-08-19 00:10

import django.db.models.deletion
import teleconsulta.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0015_fichapublica_precio_consulta'),
        ('teleconsulta', '0002_teleconsultasesion_derivacion_motivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudUrgencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=30)),
                ('cedula', models.CharField(blank=True, max_length=20)),
                ('motivo', models.TextField(blank=True)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('EN_COLA', 'En cola'), ('TOMADA', 'Tomada por un médico'), ('CANCELADA', 'Cancelada')], default='EN_COLA', max_length=20)),
                ('token', models.CharField(default=teleconsulta.models._nuevo_token, max_length=96, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('tomada_en', models.DateTimeField(blank=True, null=True)),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urgencias_tomadas', to='medico.medico')),
                ('sesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urgencia_origen', to='teleconsulta.teleconsultasesion')),
            ],
            options={
                'verbose_name': 'Solicitud de urgencia',
                'verbose_name_plural': 'Solicitudes de urgencia',
                'ordering': ['creado'],
            },
        ),
    ]
