# Generated by Django 6.0.2 on 2026-02-04 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medico', '0001_initial'),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_atencion', models.DateTimeField(auto_now_add=True)),
                ('motivo_consulta', models.TextField(help_text='Motivo por el cual viene el paciente')),
                ('enfermedad_actual', models.TextField(help_text='Descripción detallada de la molestia')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, help_text='°C', max_digits=4, null=True)),
                ('presion_arterial', models.CharField(blank=True, help_text='Ej: 120/80', max_length=20, null=True)),
                ('pulso', models.IntegerField(blank=True, help_text='Latidos por minuto', null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, help_text='Kg', max_digits=5, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, help_text='Metros', max_digits=4, null=True)),
                ('examen_fisico', models.TextField(help_text='Hallazgos del examen físico')),
                ('diagnostico', models.TextField(help_text='Diagnóstico Presuntivo o Definitivo (CIE-10)')),
                ('tratamiento', models.TextField(help_text='Indicaciones y medicamentos')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historias_creadas', to='medico.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historias', to='paciente.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenHistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(upload_to='historias_clinicas/')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='historia.historiaclinica')),
            ],
        ),
    ]
