# Generated by Django 6.0.2 on 2026-02-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Metros o CM', max_digits=5, null=True),
        ),
    ]
