# Generated by Django 6.0.2 on 2026-02-06 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0002_alter_historiaclinica_altura'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaOftalmologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agudeza_visual_od', models.CharField(default='20/20', max_length=50, verbose_name='Agudeza Visual Ojo Der.')),
                ('agudeza_visual_oi', models.CharField(default='20/20', max_length=50, verbose_name='Agudeza Visual Ojo Izq.')),
                ('presion_intraocular_od', models.CharField(blank=True, max_length=50, verbose_name='Presión Ojo Der.')),
                ('presion_intraocular_oi', models.CharField(blank=True, max_length=50, verbose_name='Presión Ojo Izq.')),
                ('fondo_ojo', models.TextField(blank=True, verbose_name='Examen de Fondo de Ojo')),
                ('historia_clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oftalmologia', to='historia.historiaclinica')),
            ],
        ),
    ]
