# Generated by Django 6.0.2 on 2026-02-06 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0003_historiaoftalmologia'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaGinecologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fum', models.DateField(blank=True, null=True, verbose_name='Fecha Última Menstruación (FUM)')),
                ('ciclo_menstrual', models.CharField(blank=True, max_length=50, verbose_name='Regularidad del Ciclo')),
                ('gestas', models.IntegerField(default=0, verbose_name='Embarazos (Gestas)')),
                ('partos', models.IntegerField(default=0, verbose_name='Partos')),
                ('cesareas', models.IntegerField(default=0, verbose_name='Cesáreas')),
                ('abortos', models.IntegerField(default=0, verbose_name='Abortos')),
                ('anticonceptivos', models.CharField(blank=True, max_length=100, verbose_name='Método Anticonceptivo')),
                ('historia_clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ginecologia', to='historia.historiaclinica')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaPediatria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_parto', models.CharField(choices=[('NORMAL', 'Normal'), ('CESAREA', 'Cesárea')], max_length=50, verbose_name='Tipo de Parto')),
                ('apgar', models.CharField(blank=True, max_length=10, verbose_name='Test APGAR')),
                ('peso_nacimiento', models.CharField(blank=True, max_length=20, verbose_name='Peso al Nacer')),
                ('lactancia', models.CharField(choices=[('MATERNA', 'Materna Exclusiva'), ('FORMULA', 'Fórmula'), ('MIXTA', 'Mixta')], default='MATERNA', max_length=50)),
                ('vacunas_completas', models.BooleanField(default=False, verbose_name='Vacunas al día')),
                ('observaciones_crecimiento', models.TextField(blank=True, verbose_name='Desarrollo Psicomotriz')),
                ('historia_clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pediatria', to='historia.historiaclinica')),
            ],
        ),
    ]
