# Generated by Django 6.0.2 on 2026-02-06 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0004_historiaginecologia_historiapediatria'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaCardiologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riesgo', models.CharField(choices=[('BAJO', 'Bajo'), ('MODERADO', 'Moderado'), ('ALTO', 'Alto'), ('MUY_ALTO', 'Muy Alto')], max_length=20, verbose_name='Riesgo CV')),
                ('antecedentes_familiares', models.TextField(blank=True, verbose_name='Antecedentes Familiares Cardíacos')),
                ('electrocardiograma', models.TextField(blank=True, verbose_name='Resumen EKG')),
                ('ecocardiograma', models.TextField(blank=True, verbose_name='Resumen Ecocardiograma')),
                ('clase_funcional', models.CharField(choices=[('I', 'I (Sin limitaciones)'), ('II', 'II (Leve limitación)'), ('III', 'III (Marcada limitación)'), ('IV', 'IV (Incapacidad total)')], default='I', max_length=50)),
                ('historia_clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cardiologia', to='historia.historiaclinica')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaDermatologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fototipo', models.CharField(max_length=50, verbose_name='Fototipo de Piel (Fitzpatrick)')),
                ('lesion_primaria', models.CharField(max_length=100, verbose_name='Lesión Primaria (Mácula, Pápula...)')),
                ('localizacion', models.CharField(max_length=100, verbose_name='Localización')),
                ('distribucion', models.CharField(max_length=100, verbose_name='Distribución (Simétrica, Localizada...)')),
                ('biopsia', models.BooleanField(default=False, verbose_name='¿Requiere Biopsia?')),
                ('historia_clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dermatologia', to='historia.historiaclinica')),
            ],
        ),
    ]
