# Generated by Django 6.0.2 on 2026-02-06 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0005_historiacardiologia_historiadermatologia'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaOdontologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('higiene_oral', models.CharField(choices=[('BUENA', 'Buena'), ('REGULAR', 'Regular'), ('MALA', 'Mala')], default='REGULAR', max_length=20, verbose_name='Higiene Oral')),
                ('encias', models.CharField(choices=[('SANAS', 'Sanas'), ('INFLAMADAS', 'Inflamadas (Gingivitis)'), ('SANGRANTES', 'Sangrantes')], default='SANAS', max_length=50)),
                ('dientes_tratados', models.CharField(blank=True, max_length=100, verbose_name='Dientes / Piezas (Ej: 18, 24, 36)')),
                ('procedimiento', models.TextField(verbose_name='Procedimiento Realizado (Obturación, Exodoncia, Profilaxis...)')),
                ('proxima_cita', models.DateField(blank=True, null=True, verbose_name='Próxima Cita / Control')),
                ('historia_clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='odontologia', to='historia.historiaclinica')),
            ],
        ),
    ]
