# Generated by Django 6.0.2 on 2026-02-06 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0006_historiaodontologia'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaNutricion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imc', models.CharField(blank=True, max_length=10, verbose_name='IMC Calculado')),
                ('grasa_corporal', models.CharField(blank=True, max_length=20, verbose_name='% Grasa Corporal')),
                ('masa_muscular', models.CharField(blank=True, max_length=20, verbose_name='% Masa Muscular')),
                ('circunferencia_cintura', models.CharField(blank=True, max_length=20, verbose_name='Cintura (cm)')),
                ('circunferencia_cadera', models.CharField(blank=True, max_length=20, verbose_name='Cadera (cm)')),
                ('tipo_dieta', models.TextField(verbose_name='Plan Alimenticio / Tipo de Dieta')),
                ('historia_clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutricion', to='historia.historiaclinica')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaPsicologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apariencia_comportamiento', models.TextField(verbose_name='Apariencia y Comportamiento')),
                ('estado_animo', models.CharField(max_length=100, verbose_name='Estado de Ánimo / Afecto')),
                ('funciones_cognitivas', models.TextField(blank=True, verbose_name='Atención, Memoria, Lenguaje')),
                ('sueno_apetito', models.CharField(blank=True, max_length=100, verbose_name='Sueño y Apetito')),
                ('plan_sesiones', models.TextField(verbose_name='Plan Terapéutico / Frecuencia')),
                ('historia_clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psicologia', to='historia.historiaclinica')),
            ],
        ),
    ]
