# Generated by Django 6.0.2 on 2026-02-06 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0007_historianutricion_historiapsicologia'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaOtorrino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otoscopia_od', models.CharField(default='Conducto permeable, Membrana timpánica íntegra', max_length=100, verbose_name='Oído Derecho')),
                ('otoscopia_oi', models.CharField(default='Conducto permeable, Membrana timpánica íntegra', max_length=100, verbose_name='Oído Izquierdo')),
                ('rinoscopia', models.TextField(blank=True, verbose_name='Fosas Nasales / Cornetes')),
                ('tabique', models.CharField(choices=[('CENTRADO', 'Centrado'), ('DESVIADO_D', 'Desviado Derecha'), ('DESVIADO_I', 'Desviado Izquierda')], default='CENTRADO', max_length=50)),
                ('orofaringe', models.TextField(blank=True, verbose_name='Boca / Faringe / Amígdalas')),
                ('audiometria', models.CharField(blank=True, max_length=100, verbose_name='Resumen Audiometría')),
                ('historia_clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otorrino', to='historia.historiaclinica')),
            ],
        ),
    ]
