# Generated by Django 6.0.2 on 2026-02-09 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0008_historiaotorrino'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaTraumatologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona_afectada', models.CharField(max_length=100, verbose_name='Zona Afectada (Ej: Rodilla Der)')),
                ('mecanismo_lesion', models.TextField(blank=True, verbose_name='Mecanismo de Lesión (Caída, Deportivo...)')),
                ('movilidad', models.CharField(default='Completos / Sin limitación', max_length=100, verbose_name='Arcos de Movilidad (ROM)')),
                ('fuerza_muscular', models.CharField(default='5/5 (Normal)', max_length=50, verbose_name='Fuerza (Daniels 1-5)')),
                ('sensibilidad', models.CharField(default='Conservada', max_length=100, verbose_name='Sensibilidad / Reflejos')),
                ('pruebas_especiales', models.TextField(blank=True, verbose_name='Pruebas Específicas (Cajón, Lachman...)')),
                ('plan_rehabilitacion', models.TextField(blank=True, verbose_name='Plan de Rehabilitación / Fisioterapia')),
                ('historia_clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='traumatologia', to='historia.historiaclinica')),
            ],
        ),
    ]
