# Generated by Django 6.0.2 on 2026-02-19 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0009_historiatraumatologia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescripcion', models.TextField(help_text='Lista de medicamentos y dosis')),
                ('indicaciones_generales', models.TextField(blank=True, help_text='Reposo, dieta, etc.', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('historia_clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='historia.historiaclinica')),
            ],
        ),
    ]
