# Generated by Django 6.0.2 on 2026-02-19 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0010_receta'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='proxima_cita',
            field=models.DateField(blank=True, null=True),
        ),
    ]
