# Generated by Django 6.0.2 on 2026-02-19 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0011_historiaclinica_proxima_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='signos_alarma',
            field=models.TextField(blank=True, default='Fiebre persistente, dificultad para respirar, dolor abdominal intenso o pérdida del conocimiento.', null=True),
        ),
    ]
