# Generated by Django 6.0.2 on 2026-02-23 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0012_historiaclinica_signos_alarma'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaGastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dolor_abdominal', models.TextField(blank=True, null=True, verbose_name='Localización y tipo de dolor')),
                ('habito_intestinal', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hábito intestinal (Frecuencia/Consistencia)')),
                ('endoscopia_previa', models.TextField(blank=True, null=True, verbose_name='Resultados de endoscopias/colonoscopias previas')),
                ('reflejo_hepatoyugular', models.BooleanField(default=False)),
                ('observaciones_digestivas', models.TextField(blank=True, null=True)),
                ('historia_clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gastro', to='historia.historiaclinica')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaGeriatria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escala_kartz', models.CharField(blank=True, max_length=50, null=True, verbose_name='Escala de Katz (Actividades vida diaria)')),
                ('deterioro_cognitivo', models.TextField(blank=True, null=True, verbose_name='Evaluación cognitiva (Ej: Minimental)')),
                ('polifarmacia', models.TextField(blank=True, null=True, verbose_name='Lista de todos los fármacos consumidos')),
                ('riesgo_caidas', models.BooleanField(default=False, verbose_name='Antecedentes o riesgo de caídas')),
                ('soporte_familiar', models.TextField(blank=True, null=True)),
                ('historia_clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geriatria', to='historia.historiaclinica')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaPsiquiatria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examen_mental', models.TextField(blank=True, null=True, verbose_name='Descripción del examen mental actual')),
                ('ideacion_suicida', models.BooleanField(default=False, verbose_name='Presencia de ideación suicida')),
                ('medicacion_psicotropica', models.TextField(blank=True, null=True, verbose_name='Medicamentos actuales y dosis')),
                ('antecedentes_psiquiatricos', models.TextField(blank=True, null=True)),
                ('estado_conciencia', models.CharField(blank=True, max_length=100, null=True)),
                ('historia_clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psiquiatria', to='historia.historiaclinica')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaReumatologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rigidez_matutina', models.CharField(blank=True, max_length=100, null=True, verbose_name='Duración de rigidez matutina (min/horas)')),
                ('articulaciones_afectadas', models.TextField(blank=True, null=True, verbose_name='Articulaciones con dolor o inflamación')),
                ('factor_reumatoide', models.CharField(blank=True, max_length=50, null=True, verbose_name='Resultado Factor Reumatoide / Anti-CCP')),
                ('capacidad_funcional', models.TextField(blank=True, null=True)),
                ('historia_clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reumatologia', to='historia.historiaclinica')),
            ],
        ),
    ]
