# Generated by Django 6.0.2 on 2026-02-25 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
        ('historia', '0013_historiagastro_historiageriatria_historiapsiquiatria_and_more'),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Triaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, help_text='Peso en kg', max_digits=5)),
                ('talla', models.DecimalField(decimal_places=2, help_text='Talla en cm', max_digits=5)),
                ('presion_arterial', models.CharField(max_length=20)),
                ('frecuencia_cardiaca', models.IntegerField(help_text='LPM')),
                ('temperatura', models.DecimalField(decimal_places=1, help_text='°C', max_digits=4)),
                ('saturacion_oxigeno', models.IntegerField(help_text='% SpO2')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='triaje', to='citas.cita')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
        ),
    ]
