# Generated by Django 6.0.2 on 2026-02-27 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0014_triaje'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historiaclinica',
            old_name='proxima_cita',
            new_name='proxima_cita_control',
        ),
        migrations.RenameField(
            model_name='historiaodontologia',
            old_name='proxima_cita',
            new_name='proxima_cita_control',
        ),
    ]
