# Generated by Django 6.0.2 on 2026-03-10 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0015_rename_proxima_cita_historiaclinica_proxima_cita_control_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiapediatria',
            name='archivo_pediatrico',
            field=models.FileField(blank=True, null=True, upload_to='historias/pediatria/', verbose_name='Adjuntar Carnet/Examen'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='proxima_cita_control',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
