# Generated by Django 6.0.2 on 2026-03-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0016_historiapediatria_archivo_pediatrico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='signos_alarma',
            field=models.TextField(blank=True, help_text='Instrucciones de emergencia para el paciente', null=True),
        ),
    ]
