# Generated by Django 6.0.2 on 2026-03-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0017_alter_historiaclinica_signos_alarma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='signos_alarma',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
