# Generated by Django 6.0.2 on 2026-04-21 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0018_alter_historiaclinica_signos_alarma'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaCirugia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cirugia', models.CharField(blank=True, max_length=150, null=True, verbose_name='Tipo / Nombre de la cirugía')),
                ('clasificacion_asa', models.CharField(choices=[('I', 'ASA I - Sano'), ('II', 'ASA II - Enfermedad leve'), ('III', 'ASA III - Enfermedad grave'), ('IV', 'ASA IV - Riesgo vital'), ('V', 'ASA V - Moribundo')], default='I', max_length=5, verbose_name='Clasificación ASA')),
                ('hallazgos_intraop', models.TextField(blank=True, null=True, verbose_name='Hallazgos intraoperatorios')),
                ('tecnica_quirurgica', models.TextField(blank=True, null=True, verbose_name='Técnica quirúrgica empleada')),
                ('complicaciones_qx', models.TextField(blank=True, null=True, verbose_name='Complicaciones')),
                ('plan_postoperatorio', models.TextField(blank=True, null=True, verbose_name='Plan postoperatorio / Indicaciones')),
                ('fecha_cirugia', models.DateField(blank=True, null=True, verbose_name='Fecha de cirugía')),
                ('historia_clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cirugia', to='historia.historiaclinica')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaEmergencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_triage', models.CharField(choices=[('1', 'Rojo - Nivel 1 (Crítico)'), ('2', 'Naranja - Nivel 2 (Urgente)'), ('3', 'Amarillo - Nivel 3 (Menos urgente)'), ('4', 'Verde - Nivel 4 (No urgente)'), ('5', 'Azul - Nivel 5 (Sin urgencia)')], default='3', max_length=3, verbose_name='Nivel de Triage (MSP)')),
                ('mecanismo_trauma', models.TextField(blank=True, null=True, verbose_name='Mecanismo de lesión / Causa consulta emergencia')),
                ('glasgow_emergencia', models.CharField(blank=True, max_length=20, null=True, verbose_name='Glasgow (O+V+M)')),
                ('via_aerea', models.CharField(blank=True, max_length=100, null=True, verbose_name='A - Vía aérea')),
                ('respiracion_emerg', models.CharField(blank=True, max_length=100, null=True, verbose_name='B - Respiración / Ventilación')),
                ('circulacion_emerg', models.CharField(blank=True, max_length=100, null=True, verbose_name='C - Circulación / Hemorragia')),
                ('procedimientos', models.TextField(blank=True, null=True, verbose_name='Procedimientos realizados')),
                ('medicacion_urgente', models.TextField(blank=True, null=True, verbose_name='Medicación administrada en emergencia')),
                ('destino_paciente', models.CharField(choices=[('ALTA', 'Alta domiciliaria'), ('HOSP', 'Hospitalización'), ('UCI', 'UCI / Cuidados intensivos'), ('CX', 'Quirófano'), ('TRASL', 'Traslado'), ('FALL', 'Fallecimiento')], default='ALTA', max_length=10, verbose_name='Destino del paciente')),
                ('historia_clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergencias', to='historia.historiaclinica')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaEndocrinologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_diabetes', models.CharField(choices=[('DM1', 'DM Tipo 1'), ('DM2', 'DM Tipo 2'), ('GEST', 'Gestacional'), ('OTRO', 'Otro / No aplica')], default='OTRO', max_length=10, verbose_name='Tipo de Diabetes')),
                ('glucosa_ayunas', models.CharField(blank=True, max_length=20, null=True, verbose_name='Glucosa en ayunas (mg/dL)')),
                ('hba1c', models.CharField(blank=True, max_length=10, null=True, verbose_name='HbA1c (%)')),
                ('insulina_basal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Insulina / dosis actual')),
                ('tsh', models.CharField(blank=True, max_length=20, null=True, verbose_name='TSH (mUI/L)')),
                ('t3_t4', models.CharField(blank=True, max_length=50, null=True, verbose_name='T3 / T4 libre')),
                ('cortisol', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cortisol sérico')),
                ('objetivos_terapeuticos', models.TextField(blank=True, null=True, verbose_name='Objetivos terapéuticos / Plan')),
                ('historia_clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endocrinologia', to='historia.historiaclinica')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaMedicinaInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mucosas', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mucosas')),
                ('ganglios', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adenopatías / Ganglios')),
                ('tiroides_examen', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tiroides al examen')),
                ('examen_pulmonar', models.TextField(blank=True, null=True, verbose_name='Examen pulmonar (auscultación)')),
                ('examen_cardiaco', models.TextField(blank=True, null=True, verbose_name='Examen cardíaco (auscultación)')),
                ('examen_abdominal', models.TextField(blank=True, null=True, verbose_name='Examen abdominal')),
                ('examen_extremidades', models.TextField(blank=True, null=True, verbose_name='Extremidades / Edemas')),
                ('examenes_laboratorio', models.TextField(blank=True, null=True, verbose_name='Laboratorio / Imagen relevante')),
                ('historia_clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medicina_interna', to='historia.historiaclinica')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaNefrologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creatinina_nef', models.CharField(blank=True, max_length=20, null=True, verbose_name='Creatinina sérica (mg/dL)')),
                ('tfg', models.CharField(blank=True, max_length=20, null=True, verbose_name='TFG estimada (mL/min/1.73m²)')),
                ('proteinuria', models.CharField(blank=True, max_length=50, null=True, verbose_name='Proteinuria (mg/24h o ratio)')),
                ('urea_bun', models.CharField(blank=True, max_length=20, null=True, verbose_name='Urea / BUN')),
                ('estadio_erc', models.CharField(choices=[('1', 'ERC 1 (TFG≥90)'), ('2', 'ERC 2 (TFG 60-89)'), ('3A', 'ERC 3a (TFG 45-59)'), ('3B', 'ERC 3b (TFG 30-44)'), ('4', 'ERC 4 (TFG 15-29)'), ('5', 'ERC 5 (TFG<15)'), ('5D', 'ERC 5D - Diálisis')], default='1', max_length=5, verbose_name='Estadio ERC')),
                ('en_hemodialisis', models.BooleanField(default=False, verbose_name='En hemodiálisis')),
                ('acceso_vascular', models.CharField(blank=True, max_length=100, null=True, verbose_name='Acceso vascular')),
                ('control_pa', models.CharField(blank=True, max_length=50, null=True, verbose_name='Control de PA')),
                ('historia_clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nefrologia', to='historia.historiaclinica')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaNeurologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escala_glasgow', models.CharField(blank=True, max_length=20, null=True, verbose_name='Escala de Glasgow (O+V+M)')),
                ('pares_craneales', models.TextField(blank=True, null=True, verbose_name='Exploración de pares craneales')),
                ('fuerza_motora', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fuerza motora MMSS/MMII')),
                ('reflejos', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reflejos osteotendinosos')),
                ('coordinacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Coordinación y equilibrio')),
                ('sensibilidad_neuro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sensibilidad')),
                ('neuroimagen', models.TextField(blank=True, null=True, verbose_name='TAC / RMN / EEG (hallazgos)')),
                ('escala_nihss', models.CharField(blank=True, max_length=20, null=True, verbose_name='Escala NIHSS (si aplica ACV)')),
                ('historia_clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='neurologia', to='historia.historiaclinica')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaNeurologia_Neumologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saturacion_o2', models.CharField(blank=True, max_length=10, null=True, verbose_name='Saturación O2 (%)')),
                ('fev1', models.CharField(blank=True, max_length=20, null=True, verbose_name='FEV1 (L / %)')),
                ('fvc', models.CharField(blank=True, max_length=20, null=True, verbose_name='FVC (L / %)')),
                ('relacion_fev1_fvc', models.CharField(blank=True, max_length=20, null=True, verbose_name='Relación FEV1/FVC')),
                ('patron_espirometrico', models.CharField(choices=[('NORMAL', 'Normal'), ('OBSTR', 'Obstructivo'), ('REST', 'Restrictivo'), ('MIXTO', 'Mixto')], default='NORMAL', max_length=10, verbose_name='Patrón espirométrico')),
                ('tabaquismo', models.CharField(choices=[('NO', 'No fumador'), ('EX', 'Ex-fumador'), ('SI', 'Fumador activo')], default='NO', max_length=5, verbose_name='Tabaquismo')),
                ('indice_paquete_anio', models.CharField(blank=True, max_length=20, null=True, verbose_name='Índice paquete/año')),
                ('rx_tac_torax', models.TextField(blank=True, null=True, verbose_name='Rx / TAC de tórax (hallazgos)')),
                ('historia_clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='neumologia', to='historia.historiaclinica')),
            ],
            options={
                'verbose_name': 'Historia Neumología',
            },
        ),
        migrations.CreateModel(
            name='HistoriaUrologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sintomas_miccionales', models.CharField(blank=True, max_length=100, null=True, verbose_name='Síntomas miccionales / Score IPSS')),
                ('psa', models.CharField(blank=True, max_length=20, null=True, verbose_name='PSA total (ng/mL)')),
                ('creatinina_uro', models.CharField(blank=True, max_length=20, null=True, verbose_name='Creatinina sérica (mg/dL)')),
                ('urocultivo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Urocultivo / Uroanálisis')),
                ('ecografia', models.TextField(blank=True, null=True, verbose_name='Ecografía renal / Prostática (hallazgos)')),
                ('residuo_postmiccional', models.CharField(blank=True, max_length=50, null=True, verbose_name='Residuo postmiccional (mL)')),
                ('cistoscopia', models.TextField(blank=True, null=True, verbose_name='Cistoscopia (hallazgos)')),
                ('historia_clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='urologia', to='historia.historiaclinica')),
            ],
        ),
    ]
