# Generated by Django 6.0.2 on 2026-04-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0019_nuevas_especialidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='antecedentes_familiares',
            field=models.TextField(blank=True, help_text='Enfermedades hereditarias o relevantes en familiares directos', null=True, verbose_name='Antecedentes Familiares'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='antecedentes_personales',
            field=models.TextField(blank=True, help_text='Enfermedades previas, cirugías, alergias, medicamentos actuales', null=True, verbose_name='Antecedentes Personales'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='plan_educacional',
            field=models.TextField(blank=True, help_text='Instrucciones y educación entregada al paciente', null=True, verbose_name='Plan Educacional'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='revision_sistemas',
            field=models.TextField(blank=True, help_text='Síntomas positivos y negativos relevantes por sistemas', null=True, verbose_name='Revisión de Órganos y Sistemas'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='tipo_diagnostico',
            field=models.CharField(choices=[('PRESUNTIVO', 'Presuntivo'), ('DEFINITIVO', 'Definitivo')], default='PRESUNTIVO', max_length=12, verbose_name='Tipo de Diagnóstico'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='diagnostico',
            field=models.TextField(help_text='Diagnóstico CIE-10'),
        ),
    ]
