# Generated by Django 6.0.2 on 2026-05-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0020_campos_msp_formulario002'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='receta_pdf',
            field=models.FileField(blank=True, null=True, upload_to='recetas/'),
        ),
    ]
