# Generated by Django 6.0.2 on 2026-05-05 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0021_add_receta_pdf'),
        ('paciente', '0003_add_mascota'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='mascota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historias', to='paciente.mascota'),
        ),
        migrations.CreateModel(
            name='HistoriaVeterinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, help_text='°C', max_digits=4, null=True)),
                ('frecuencia_card', models.IntegerField(blank=True, null=True, verbose_name='Frecuencia cardiaca (lpm)')),
                ('frecuencia_resp', models.IntegerField(blank=True, null=True, verbose_name='Frecuencia respiratoria (rpm)')),
                ('peso_actual', models.DecimalField(blank=True, decimal_places=2, help_text='Kg', max_digits=6, null=True)),
                ('condicion_corporal', models.CharField(blank=True, choices=[('1', '1 - Caquexia'), ('2', '2 - Bajo peso'), ('3', '3 - Ideal'), ('4', '4 - Sobrepeso'), ('5', '5 - Obesidad')], max_length=20)),
                ('vacunas_aplicadas', models.TextField(blank=True, verbose_name='Vacunas aplicadas hoy')),
                ('proxima_vacuna', models.DateField(blank=True, null=True)),
                ('desparasitacion', models.TextField(blank=True, verbose_name='Desparasitación aplicada')),
                ('proxima_desparasitacion', models.DateField(blank=True, null=True)),
                ('mucosas', models.CharField(blank=True, choices=[('NORMAL', 'Rosadas (Normal)'), ('PALIDAS', 'Pálidas'), ('CIANOTICAS', 'Cianóticas'), ('ICTERICAS', 'Ictéricas')], max_length=50)),
                ('hidratacion', models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('LEVE', 'Deshidratación leve (5%)'), ('MODERADA', 'Moderada (8%)'), ('SEVERA', 'Severa (>10%)')], max_length=30)),
                ('observaciones_examen', models.TextField(blank=True, verbose_name='Observaciones del examen físico')),
                ('historia_clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='veterinaria', to='historia.historiaclinica')),
            ],
        ),
    ]
