# Generated by Django 6.0.2 on 2026-06-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0022_add_mascota_y_veterinaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoCIE10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='Código CIE-10')),
                ('descripcion', models.CharField(db_index=True, max_length=300, verbose_name='Descripción')),
                ('capitulo', models.CharField(blank=True, max_length=120, verbose_name='Capítulo')),
            ],
            options={
                'verbose_name': 'Código CIE-10',
                'verbose_name_plural': 'Códigos CIE-10',
                'ordering': ['codigo'],
            },
        ),
    ]
