# Generated by Django 6.0.2 on 2026-08-07 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0023_codigocie10'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaodontologia',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='historiaodontologia',
            name='odontograma',
            field=models.JSONField(blank=True, default=dict, verbose_name='Odontograma'),
        ),
        migrations.AddField(
            model_name='historiaodontologia',
            name='plan_tratamiento',
            field=models.TextField(blank=True, verbose_name='Plan de tratamiento'),
        ),
        migrations.AlterField(
            model_name='historiaodontologia',
            name='procedimiento',
            field=models.TextField(blank=True, verbose_name='Procedimiento Realizado (Obturación, Exodoncia, Profilaxis...)'),
        ),
    ]
