# Generated by Django 6.0.2 on 2026-04-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_alter_cita_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('E', 'En Espera'), ('A', 'Atendido'), ('C', 'Cancelado')], default='P', max_length=20),
        ),
    ]
