# Generated by Django 6.0.2 on 2026-05-05 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_alter_cita_estado'),
        ('paciente', '0003_add_mascota'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='mascota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='paciente.mascota'),
        ),
    ]
