# Generated by Django 6.0.2 on 2026-08-05 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_add_mascota_a_cita'),
        ('medico', '0014_fichapublica'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=30)),
                ('motivo', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('contactada', 'Contactada'), ('agendada', 'Agendada'), ('descartada', 'Descartada')], default='pendiente', max_length=20)),
                ('origen', models.CharField(default='ficha_publica', max_length=40)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cita', to='medico.medico')),
            ],
            options={
                'verbose_name': 'Solicitud de cita',
                'verbose_name_plural': 'Solicitudes de cita',
                'ordering': ['-creado_en'],
            },
        ),
    ]
