# Generated by Django 6.0.2 on 2026-08-06 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_solicitudcita'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcita',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitud_origen', to='citas.cita'),
        ),
    ]
