# Generated by Django 6.0.2 on 2026-08-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0006_solicitudcita_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='modalidad',
            field=models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('TELECONSULTA', 'Teleconsulta'), ('TELEINTERCONSULTA', 'Teleinterconsulta'), ('TELEMONITOREO', 'Telemonitoreo')], default='PRESENCIAL', help_text='Presencial o modalidad remota (telesalud)', max_length=20),
        ),
    ]
